### ISSUE TITLE
1.0.7 breaks with PHP 7.x

### ISSUE THREAD

**Issue by gerhard-boden** [ttreeagency/DimensionKeeper#4]
Since no PHP 7.1 requirement is defined and Neos 3.x still supports PHP 7.x, the bufix release 1.0.7 breaks compatibility.  Oddly enough I can not find the change log but the file https://github.com/ttreeagency/DimensionKeeper/blob/1.0.7/Classes/Keeper.php#L78 unterwent some change in this release, including the usage of ``?NodeInterface``.

Please either raise minimum PHP version and release a new major, or remove the nullable type with new bugfix release (didn't open PR since it's your decision how to go forth)

Thanks 😃

**Comment by dfeyer** [comment]
The tag 1.0.7 is on detached head ... my bad :( Let's fix that a release a PHP 7.x for the next minor version ;)

**Comment by dfeyer** [comment]
So something was really wrong with the 1.0.7 release, please test the 1.0.8 and ping me if you have any issue

**Comment by gerhard-boden** [comment]
Thanks for that ultra fast fix, 1.0.8 resolves the issue!
